# Generated by Django 4.2.9 on 2024-02-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
